export const pantryIngredients = [
  'ayam',
  'daging',
  'ikan',
  'udang',
  'telur',
  'kentang',
  'tomato',
  'bawang merah',
  'bawang putih',
  'cili',
  'santan',
  'sos tiram',
  'kicap manis',
  'kicap cair',
  'beras',
  'mee',
  'spaghetti',
  'roti',
  'bayam',
  'sawi',
  'brokoli',
  'lobak merah',
  'halia',
  'serai',
  'daun kunyit',
  'serbuk kari',
  'minyak',
  'garam',
  'gula',
  'lada hitam',
]

export const recipeCatalog = [
  {
    id: 'r1',
    title: 'Ayam Kicap Petir 15 Minit',
    mealType: 'quick',
    ingredients: ['ayam', 'kicap manis', 'bawang putih', 'minyak', 'garam'],
    optional: ['cili', 'lada hitam'],
    steps: [
      'Panaskan minyak, tumis bawang putih hingga wangi.',
      'Masukkan ayam dan goreng hingga separa masak.',
      'Tambah kicap manis, garam, sedikit air, kacau 6-8 minit.',
      'Masuk cili dan lada hitam, siap untuk hidang.',
    ],
    timeMinutes: 15,
  },
  {
    id: 'r2',
    title: 'Telur Dadar Bawang Turbo',
    mealType: 'quick',
    ingredients: ['telur', 'bawang merah', 'garam', 'minyak'],
    optional: ['cili'],
    steps: [
      'Pukul telur dengan bawang merah, garam dan cili.',
      'Panaskan minyak, tuang telur, masak hingga keemasan dua sisi.',
      'Padankan dengan nasi panas.',
    ],
    timeMinutes: 10,
  },
  {
    id: 'r3',
    title: 'Nasi Goreng Fridge Rescue',
    mealType: 'quick',
    ingredients: ['beras', 'telur', 'bawang putih', 'kicap cair', 'minyak'],
    optional: ['ayam', 'udang', 'lobak merah'],
    steps: [
      'Gunakan nasi sejuk semalam untuk tekstur terbaik.',
      'Tumis bawang putih, tambah ayam/udang jika ada.',
      'Masuk telur, kemudian nasi dan kicap cair.',
      'Kacau laju 4-5 minit hingga sebati.',
    ],
    timeMinutes: 18,
  },
  {
    id: 'r4',
    title: 'Kari Ayam Ringkas',
    mealType: 'comfort',
    ingredients: ['ayam', 'serbuk kari', 'santan', 'bawang merah', 'minyak', 'garam'],
    optional: ['kentang', 'halia'],
    steps: [
      'Tumis bawang merah dan halia sehingga naik bau.',
      'Masukkan serbuk kari dengan sedikit air hingga jadi pes.',
      'Masukkan ayam dan kentang, kacau 5 minit.',
      'Tambah santan, reneh 15 minit, perasakan garam.',
    ],
    timeMinutes: 30,
  },
  {
    id: 'r5',
    title: 'Sup Ayam Halia',
    mealType: 'healthy',
    ingredients: ['ayam', 'halia', 'bawang putih', 'garam'],
    optional: ['lobak merah', 'sawi'],
    steps: [
      'Rebus ayam dengan halia dan bawang putih.',
      'Tambah air secukupnya, reneh 20 minit.',
      'Masukkan sayur jika ada, akhir sekali garam.',
    ],
    timeMinutes: 28,
  },
  {
    id: 'r6',
    title: 'Udang Sos Tiram Kilat',
    mealType: 'quick',
    ingredients: ['udang', 'sos tiram', 'bawang putih', 'minyak'],
    optional: ['brokoli', 'lada hitam'],
    steps: [
      'Tumis bawang putih hingga kekuningan.',
      'Masukkan udang dan kacau hingga bertukar warna.',
      'Tambah sos tiram dan brokoli, masak 4 minit.',
      'Perasakan lada hitam dan terus hidang.',
    ],
    timeMinutes: 12,
  },
  {
    id: 'r7',
    title: 'Spaghetti Cili Bawang',
    mealType: 'quick',
    ingredients: ['spaghetti', 'bawang putih', 'cili', 'minyak', 'garam'],
    optional: ['udang', 'ayam'],
    steps: [
      'Rebus spaghetti hingga al dente.',
      'Tumis bawang putih dan cili dalam minyak zaitun/minyak biasa.',
      'Masukkan protein pilihan dan spaghetti, gaul sebati.',
      'Perasakan garam sebelum hidang.',
    ],
    timeMinutes: 20,
  },
  {
    id: 'r8',
    title: 'Ikan Bakar Pan Dengan Serai',
    mealType: 'healthy',
    ingredients: ['ikan', 'serai', 'halia', 'garam', 'minyak'],
    optional: ['cili', 'daun kunyit'],
    steps: [
      'Lumurkan ikan dengan garam, halia dan serai ketuk.',
      'Panaskan pan, sapu minyak dan bakar ikan kedua-dua sisi.',
      'Tambahkan daun kunyit/cili untuk aroma.',
    ],
    timeMinutes: 22,
  },
]
